@echo off
echo Downloading blog images...
cd /d "%~dp0"

if not exist "assets\blog-images-all" mkdir "assets\blog-images-all"

curl -L -o "assets\blog-images-all\Gastric-Cancer.png" "https://drvijayanandreddy.com/wp-content/uploads/2022/11/Gastric-Cancer.png"
curl -L -o "assets\blog-images-all\Gastric-Cancer-214x300.png" "https://drvijayanandreddy.com/wp-content/uploads/2022/11/Gastric-Cancer-214x300.png"
curl -L -o "assets\blog-images-all\Stomach-Or.webp" "https://drvijayanandreddy.com/wp-content/uploads/2022/11/Stomach-Or.webp"
curl -L -o "assets\blog-images-all\stomach.png" "https://drvijayanandreddy.com/wp-content/uploads/2022/11/stomach.png"
curl -L -o "assets\blog-images-all\stomach-cancer.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2022/11/stomach-cancer.jpg"
curl -L -o "assets\blog-images-all\stomach-1.png" "https://drvijayanandreddy.com/wp-content/uploads/2022/11/stomach-1.png"
curl -L -o "assets\blog-images-all\Liver-Cancer-Symptoms-Signs-Causes-Treatment-2.jpeg" "https://drvijayanandreddy.com/wp-content/uploads/2023/11/Liver-Cancer-Symptoms-Signs-Causes-Treatment-2.jpeg"
curl -L -o "assets\blog-images-all\Liver-Cancer-Symptoms-Signs-Causes-Treatment.jpeg" "https://drvijayanandreddy.com/wp-content/uploads/2023/11/Liver-Cancer-Symptoms-Signs-Causes-Treatment.jpeg"
curl -L -o "assets\blog-images-all\The-evolution-and-impact-of-Immunotherapy.jpeg" "https://drvijayanandreddy.com/wp-content/uploads/2023/11/The-evolution-and-impact-of-Immunotherapy.jpeg"
curl -L -o "assets\blog-images-all\Proton-Therapy.jpeg" "https://drvijayanandreddy.com/wp-content/uploads/2023/11/Proton-Therapy.jpeg"
curl -L -o "assets\blog-images-all\Colon-Cancer-Diet-Foods-to-eat-and-what-to-avoid.jpeg" "https://drvijayanandreddy.com/wp-content/uploads/2023/11/Colon-Cancer-Diet-Foods-to-eat-and-what-to-avoid.jpeg"
curl -L -o "assets\blog-images-all\Understanding-Colon-Cancer-Symptoms-Causes-and-Prevention.jpeg" "https://drvijayanandreddy.com/wp-content/uploads/2023/11/Understanding-Colon-Cancer-Symptoms-Causes-and-Prevention.jpeg"
curl -L -o "assets\blog-images-all\Understanding-Cancer-Dispelling-Myths-and-Presenting-Facts-1.jpeg" "https://drvijayanandreddy.com/wp-content/uploads/2023/11/Understanding-Cancer-Dispelling-Myths-and-Presenting-Facts-1.jpeg"
curl -L -o "assets\blog-images-all\Understanding-Cancer-Dispelling-Myths-and-Presenting-Facts.jpeg" "https://drvijayanandreddy.com/wp-content/uploads/2023/11/Understanding-Cancer-Dispelling-Myths-and-Presenting-Facts.jpeg"
curl -L -o "assets\blog-images-all\WhatsApp-Image-2023-11-28-at-5.16.07-PM.jpeg" "https://drvijayanandreddy.com/wp-content/uploads/2023/11/WhatsApp-Image-2023-11-28-at-5.16.07-PM.jpeg"
curl -L -o "assets\blog-images-all\Radiation-Therapy-for-Cancer.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2023/12/Radiation-Therapy-for-Cancer.jpg"
curl -L -o "assets\blog-images-all\vijay-anand-reddy-thumbnail-Esophageal-Cancer.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2023/12/vijay-anand-reddy-thumbnail-Esophageal-Cancer.jpg"
curl -L -o "assets\blog-images-all\SURAJ-SIR-thumbnal-1.png" "https://drvijayanandreddy.com/wp-content/uploads/2023/12/SURAJ-SIR-thumbnal-1.png"
curl -L -o "assets\blog-images-all\vijay-anand-Reddy-thumbnail.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/01/vijay-anand-Reddy-thumbnail.jpg"
curl -L -o "assets\blog-images-all\vijay-anand-Reddy-throid-cancer.png" "https://drvijayanandreddy.com/wp-content/uploads/2024/01/vijay-anand-Reddy-throid-cancer.png"
curl -L -o "assets\blog-images-all\Chemotherapy-and-Radiation-Therapy.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/01/Chemotherapy-and-Radiation-Therapy.jpg"
curl -L -o "assets\blog-images-all\Radiation-Therapy-vijay-anand-Reddy-thumbnail.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/01/Radiation-Therapy-vijay-anand-Reddy-thumbnail.jpg"
curl -L -o "assets\blog-images-all\vijay-anand-reddy-thumbnail-medical-onology1.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/02/vijay-anand-reddy-thumbnail-medical-onology1.jpg"
curl -L -o "assets\blog-images-all\Cancer-care-.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/02/Cancer-care-.jpg"
curl -L -o "assets\blog-images-all\Breast-cancer1.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/02/Breast-cancer1.jpg"
curl -L -o "assets\blog-images-all\Cancer-risk.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/03/Cancer-risk.jpg"
curl -L -o "assets\blog-images-all\Advancements-in-rediation.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/03/Advancements-in-rediation.jpg"
curl -L -o "assets\blog-images-all\Brest-cancer-1.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/03/Brest-cancer-1.jpg"
curl -L -o "assets\blog-images-all\Eye-Cancer-1.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/03/Eye-Cancer-1.jpg"
curl -L -o "assets\blog-images-all\WhatsApp-Image-2024-07-08-at-11.41.18-AM.jpeg" "https://drvijayanandreddy.com/wp-content/uploads/2024/07/WhatsApp-Image-2024-07-08-at-11.41.18-AM.jpeg"
curl -L -o "assets\blog-images-all\27160203-201a33b0-4df8-4b17-9aae-a339a0df39af-scaled.avif" "https://drvijayanandreddy.com/wp-content/uploads/2024/07/27160203-201a33b0-4df8-4b17-9aae-a339a0df39af-scaled.avif"
curl -L -o "assets\blog-images-all\vijay-anand-reddy-thumbnail-medical-onology-1-2.png" "https://drvijayanandreddy.com/wp-content/uploads/2024/07/vijay-anand-reddy-thumbnail-medical-onology-1-2.png"
curl -L -o "assets\blog-images-all\vijay-anand-reddy-thumbnail-medical-onology-3.png" "https://drvijayanandreddy.com/wp-content/uploads/2024/07/vijay-anand-reddy-thumbnail-medical-onology-3.png"
curl -L -o "assets\blog-images-all\image.png" "https://drvijayanandreddy.com/wp-content/uploads/2024/07/image.png"
curl -L -o "assets\blog-images-all\Breast-Cancer-1.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/07/Breast-Cancer-1.jpg"
curl -L -o "assets\blog-images-all\image-1.png" "https://drvijayanandreddy.com/wp-content/uploads/2024/07/image-1.png"
curl -L -o "assets\blog-images-all\Is-Breast-Cancer-Considered-a-Disability2.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/07/Is-Breast-Cancer-Considered-a-Disability2.jpg"
curl -L -o "assets\blog-images-all\Chemotherapy.png" "https://drvijayanandreddy.com/wp-content/uploads/2024/07/Chemotherapy.png"
curl -L -o "assets\blog-images-all\image-2-1-1024x1024.png" "https://drvijayanandreddy.com/wp-content/uploads/2024/07/image-2-1-1024x1024.png"
curl -L -o "assets\blog-images-all\Can-Breast-Cancer-1.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/07/Can-Breast-Cancer-1.jpg"
curl -L -o "assets\blog-images-all\image-2.png" "https://drvijayanandreddy.com/wp-content/uploads/2024/07/image-2.png"
curl -L -o "assets\blog-images-all\image.jpeg" "https://drvijayanandreddy.com/wp-content/uploads/2024/07/image.jpeg"
curl -L -o "assets\blog-images-all\image-2-1.png" "https://drvijayanandreddy.com/wp-content/uploads/2024/07/image-2-1.png"
curl -L -o "assets\blog-images-all\Advancements-in-Chemotherapy-Latest-Treatments-and-Technologies.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/08/Advancements-in-Chemotherapy-Latest-Treatments-and-Technologies.jpg"
curl -L -o "assets\blog-images-all\Managing-Side-Effects-of-Cancer-Treatments-Tips-and-Advice.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/08/Managing-Side-Effects-of-Cancer-Treatments-Tips-and-Advice.jpg"
curl -L -o "assets\blog-images-all\The-Multidisciplinary-Approach-in-Medical-Oncology.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/08/The-Multidisciplinary-Approach-in-Medical-Oncology.jpg"
curl -L -o "assets\blog-images-all\Nutrition-and-Diet-During-Cancer-Treatment-What-You-Need-to-Know.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2024/08/Nutrition-and-Diet-During-Cancer-Treatment-What-You-Need-to-Know.jpg"
curl -L -o "assets\blog-images-all\Everything-You-Need-to-Know-About-Cervical-Cancer-Causes-Symptoms-and-Treatments.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2025/01/Everything-You-Need-to-Know-About-Cervical-Cancer-Causes-Symptoms-and-Treatments.jpg"
curl -L -o "assets\blog-images-all\WhatsApp-Image-2025-01-17-at-3.50.37-PM.jpeg" "https://drvijayanandreddy.com/wp-content/uploads/2025/01/WhatsApp-Image-2025-01-17-at-3.50.37-PM.jpeg"
curl -L -o "assets\blog-images-all\Understanding-Eye-Melanoma-Symptoms-Causes-Treatment-and-Prevention.webp" "https://drvijayanandreddy.com/wp-content/uploads/2025/01/Understanding-Eye-Melanoma-Symptoms-Causes-Treatment-and-Prevention.webp"
curl -L -o "assets\blog-images-all\Why-Prevention-Is-the-Best-Cure-–-Cancer-Screening-Guidelines.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2025/06/Why-Prevention-Is-the-Best-Cure-–-Cancer-Screening-Guidelines.jpg"
curl -L -o "assets\blog-images-all\10-Early-Warning-Signs-of-Cancer-You-Should-Never-Ignore-visual-selection.png" "https://drvijayanandreddy.com/wp-content/uploads/2025/06/10-Early-Warning-Signs-of-Cancer-You-Should-Never-Ignore-visual-selection.png"
curl -L -o "assets\blog-images-all\Why-Prevention-Is-the-Best-Cure-–-Cancer-Screening-Guidelines-1.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2025/06/Why-Prevention-Is-the-Best-Cure-–-Cancer-Screening-Guidelines-1.jpg"
curl -L -o "assets\blog-images-all\i-2025-06-21T142820.072.webp" "https://drvijayanandreddy.com/wp-content/uploads/2025/06/i-2025-06-21T142820.072.webp"
curl -L -o "assets\blog-images-all\i-2025-06-21T143847.458.png" "https://drvijayanandreddy.com/wp-content/uploads/2025/06/i-2025-06-21T143847.458.png"
curl -L -o "assets\blog-images-all\i-2025-06-21T143719.762.png" "https://drvijayanandreddy.com/wp-content/uploads/2025/06/i-2025-06-21T143719.762.png"
curl -L -o "assets\blog-images-all\image-1024x353.png" "https://drvijayanandreddy.com/wp-content/uploads/2025/06/image-1024x353.png"
curl -L -o "assets\blog-images-all\Immunotherapy-vs-Chemotherapy-Which-is-Better-for-Cancer-Treatment.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2025/06/Immunotherapy-vs-Chemotherapy-Which-is-Better-for-Cancer-Treatment.jpg"
curl -L -o "assets\blog-images-all\image.png" "https://drvijayanandreddy.com/wp-content/uploads/2025/06/image.png"
curl -L -o "assets\blog-images-all\steptodown.com638121-1024x614.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2025/07/steptodown.com638121-1024x614.jpg"
curl -L -o "assets\blog-images-all\Top-Signs-of-Cancer-You-Should-Never-Ignore-Early-Detection-Saves-Lives.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2025/07/Top-Signs-of-Cancer-You-Should-Never-Ignore-Early-Detection-Saves-Lives.jpg"
curl -L -o "assets\blog-images-all\blgo-1.webp" "https://drvijayanandreddy.com/wp-content/uploads/2025/07/blgo-1.webp"
curl -L -o "assets\blog-images-all\How-Technology-Is-Changing-the-Way-We-Fight-Cancer-1.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2025/09/How-Technology-Is-Changing-the-Way-We-Fight-Cancer-1.jpg"
curl -L -o "assets\blog-images-all\How-Technology-Is-Changing-the-Way-We-Fight-Cancer-2.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2025/09/How-Technology-Is-Changing-the-Way-We-Fight-Cancer-2.jpg"
curl -L -o "assets\blog-images-all\How-Technology-Is-Changing-the-Way-We-Fight-Cancer-3.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2025/10/How-Technology-Is-Changing-the-Way-We-Fight-Cancer-3.jpg"
curl -L -o "assets\blog-images-all\The-Fundamental-Biological-Barrier-visual-selection.png" "https://drvijayanandreddy.com/wp-content/uploads/2025/10/The-Fundamental-Biological-Barrier-visual-selection.png"
curl -L -o "assets\blog-images-all\How-Technology-Is-Changing-the-Way-We-Fight-Cancer.png" "https://drvijayanandreddy.com/wp-content/uploads/2025/10/How-Technology-Is-Changing-the-Way-We-Fight-Cancer.png"
curl -L -o "assets\blog-images-all\Pioneering-Breast-Cancer-Treatments-Next-Generation-Therapies-for-Todays-Patients.jpeg" "https://drvijayanandreddy.com/wp-content/uploads/2023/11/Pioneering-Breast-Cancer-Treatments-Next-Generation-Therapies-for-Todays-Patients.jpeg"
curl -L -o "assets\blog-images-all\How-Technology-Is-Changing-the-Way-We-Fight-Cancer-5.png" "https://drvijayanandreddy.com/wp-content/uploads/2025/11/How-Technology-Is-Changing-the-Way-We-Fight-Cancer-5.png"
curl -L -o "assets\blog-images-all\How-Technology-Is-Changing-the-Way-We-Fight-Cancer-2.jpg" "https://drvijayanandreddy.com/wp-content/uploads/2025/11/How-Technology-Is-Changing-the-Way-We-Fight-Cancer-2.jpg"

echo Done!
pause